version: "3.7"

services: 
 app: 
  image: ahmed2786/dotnet-album-viewer
  build: 
   context: .
   dockerfile: Dockerfile		
  ports: 
   - 80:80
  depends_on: 
   - db
  environment: 
   - "Data:Provider=MySQL"
   - "Data:ConnectionString=Server=db;Port=4000;Database=AlbumViewer;User=root;SslMode=None"

 db: 
  image: dockersamples/tidb:nanoserver-sac2016